;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        backward-up-list
        c-electric-delete-forward
        c-electric-paren
        c-electric-star
        cargo-process-run
        cider-eval-last-sexp-and-replace
        cljr-raise-sexp
        cljr-slash
        clojure-sort-ns
        company-indent-or-complete-common
        counsel-yank-pop
        dabbrev-expand
        forward-sexp
        handle-switch-frame
        hs-toggle-hiding
        ivy-switch-buffer
        kill-region
        kill-sexp
        mark-sexp
        move-to-window-line-top-bottom
        org-delete-char
        org-self-insert-command
        outline-show-children
        paredit-backward
        paredit-backward-down
        paredit-backward-slurp-sexp
        paredit-backward-up
        paredit-close-round
        paredit-close-square
        paredit-delete-indentation
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-kill
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-splice-sexp
        reposition-window
        rjsx-delete-creates-full-tag
        suspend-frame
        toggle-truncate-lines
        zap-up-to-char
        cider-eval-last-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cider-load-buffer
        counsel-find-file
        end-of-buffer
        goto-line
        swiper-isearch
        ))
