;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        clojure-sort-ns
        counsel-yank-pop
        dabbrev-expand
        handle-switch-frame
        hs-toggle-hiding
        ivy-switch-buffer
        kill-sexp
        paredit-backward
        paredit-close-square
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        reposition-window
        suspend-frame
        toggle-truncate-lines
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        paredit-close-parenthesis-and-newline
        paredit-kill
        swiper-isearch
        ))
