;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        cargo-process-run
        cljr-raise-sexp
        cljr-slash
        clojure-sort-ns
        company-indent-or-complete-common
        counsel-yank-pop
        dabbrev-expand
        forward-sexp
        handle-switch-frame
        hs-toggle-hiding
        ivy-switch-buffer
        kill-region
        kill-sexp
        mark-sexp
        org-self-insert-command
        paredit-backward
        paredit-backward-up
        paredit-close-square
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-slurp-sexp
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-splice-sexp
        reposition-window
        rjsx-delete-creates-full-tag
        suspend-frame
        toggle-truncate-lines
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cider-eval-last-sexp
        cider-load-buffer
        end-of-buffer
        mouse-set-region
        paredit-close-parenthesis-and-newline
        paredit-kill
        swiper-isearch
        ))
